name: Docker Build and Test Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker
        uses: docker/setup-docker-action@v2

      - name: Build Docker images
        run: make docker-build

      - name: Start Docker containers
        run: make docker-start


      - name: Clean up Docker
        run: make docker-clean
