name: Run Playwright E2E Tests
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: cd frontend && npx playwright install --with-deps

      - name: Prepare backend environment
        run: make prepare

      - name: Start backend
        run: make start-backend &
        env:
          NODE_ENV: test

      - name: Start frontend
        run: make start-frontend &
        env:
          NODE_ENV: test

      - name: Wait for backend to be ready
        run: |
          timeout 30s bash -c 'until curl -sSf http://localhost:5001/api >/dev/null; do sleep 1; done'
        shell: bash

      - name: Wait for frontend to be ready
        run: |
          timeout 30s bash -c 'until curl -sSf http://localhost:3000 >/dev/null; do sleep 1; done'
        shell: bash

      - name: Run Playwright tests
        run: cd frontend && npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
