name: Run Playwright E2E Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: taskmanager_test
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Install dependencies (root and workspaces)
        run: npm install

      - name: Install Playwright Browsers
        run: cd frontend && npx playwright install --with-deps

      - name: Prepare backend database and env
        run: make prepare

      - name: Set environment variables for DB connection
        run: echo "DB_HOST=localhost" >> $GITHUB_ENV
        run: echo "DB_PORT=5432" >> $GITHUB_ENV
        run: echo "DB_NAME=taskmanager_test" >> $GITHUB_ENV
        run: echo "DB_USER=postgres" >> $GITHUB_ENV
        run: echo "DB_PASSWORD=postgres" >> $GITHUB_ENV

      - name: Run DB migrations
        run: |
          NODE_ENV=testCI npx knex migrate:latest
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: taskmanager_test
          DB_USER: postgres
          DB_PASSWORD: postgres

      - name: Build the app (front & back)
        run: make build

      - name: Start the app (front & back)
        run: make start &
        env:
          NODE_ENV: test

      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:5001/api

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: cd frontend && npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
